#!/usr/bin/env python3
"""
Script to update move categories in PBStuff.rb based on user's provided list
"""

# Parse the user's category lists with corrected move names
categories = {
    'SLASHINGMOVE': [
        'AERIALACE', 'AIRCUTTER', 'AIRSLASH', 'AQUACUTTER', 'BEHEMOTHBLADE', 'BITTERBLADE',
        'CEASELESSEDGE', 'CROSSPOISON', 'CUT', 'FURYCUTTER', 'KOWTOWCLEAVE', 'LEAFBLADE',
        'MIGHTYCLEAVE', 'NIGHTSLASH', 'POPULATIONBOMB', 'PSYBLADE', 'PSYCHOCUT', 'RAZORLEAF',
        'RAZORSHELL', 'SACREDSWORD', 'SECRETSWORD', 'SLASH', 'SOLARBLADE', 'STONEAXE',
        'TACHYONCUTTER', 'XSCISSOR', 'GUILLOTINE', 'NIGHTFALL', 'SLASHANDBURN', 'CLEANCUT', 'TIDEBREAK'
    ],
    'PIERCINGMOVE': [
        'HORNATTACK', 'FURYATTACK', 'POISONSTING', 'TWINEEDLE', 'PECK', 'DRILLPECK', 'MEGAHORN',
        'POISONJAB', 'NEEDLEARM', 'PLUCK', 'DRILLRUN', 'HORNLEECH', 'FELLSTINGER', 'SMARTSTRIKE',
        'BRANCHPOKE', 'HORNDRILL', 'FALSESURRENDER', 'SPIRITSHACKLE', 'TRIPLEARROWS',
        'ICICLESPEAR', 'PINMISSILE', 'SPIKECANNON', 'WATERSHURIKEN', 'CURTAINSCALL',
        'SOULJAVELIN', 'TORPEDO', 'TALESEND', 'PERFORATE', 'PIERCETHEVEIL', 'THREEFOLDSTRIKE', 'EQUINOXHORN'
    ],
    'BLUDGEONINGMOVE': [
        'DRAGONTAIL', 'POISONTAIL', 'IRONTAIL', 'AQUATAIL', 'HAMMERARM', 'WOODHAMMER',
        'CRABHAMMER', 'DRAGONHAMMER', 'ICEHAMMER', 'BONECLUB', 'BONERUSH', 'SHADOWBONE',
        'POUND', 'SLAM', 'ROCKSMASH', 'BREAKINGSWIPE', 'DOUBLEIRONBASH', 'ROCKYVERDICT'
    ],
    'PUNCHINGMOVE': [
        'BULLETPUNCH', 'COMETPUNCH', 'DIZZYPUNCH', 'DOUBLEIRONBASH', 'DRAINPUNCH',
        'DYNAMICPUNCH', 'FIREPUNCH', 'FOCUSPUNCH', 'HAMMERARM', 'HEADLONGRUSH', 'ICEHAMMER',
        'ICEPUNCH', 'JETPUNCH', 'MACHPUNCH', 'MEGAPUNCH', 'METEORMASH', 'PLASMAFISTS',
        'POWERUPPUNCH', 'RAGEFIST', 'SHADOWPUNCH', 'SKYUPPERCUT', 'SURGINGSTRIKES',
        'THUNDERPUNCH', 'WICKEDBLOW', 'SUCKERPUNCH', 'GLACIALSTATE', 'STOKE', 'SHADOWBOX',
        'SHOWSTOPPER', 'LUCKYSTAR', 'SPIRITFIST'
    ],
    'KICKINGMOVE': [
        'HIJUMPKICK', 'JUMPKICK', 'ROLLINGKICK', 'DOUBLEKICK', 'TRIPLEKICK', 'LOWKICK',
        'BLAZEKICK', 'MEGAKICK', 'TROPKICK', 'TRIPLEAXEL', 'THUNDEROUSKICK', 'TRIPLEARROWS', 'AXEKICK'
    ],
    'BOMBMOVE': [
        'ACIDSPRAY', 'BARRAGE', 'BEAKBLAST', 'BULLETSEED', 'EGGBOMB', 'FOCUSBLAST',
        'MAGNETBOMB', 'MUDBOMB', 'OCTAZOOKA', 'POLLENPUFF', 'ROCKBLAST', 'ROCKWRECKER',
        'SEARINGSHOT', 'SEEDBOMB', 'SLUDGEBOMB', 'SYRUPBOMB', 'ZAPCANNON', 'UNSTABLEMATTER', 'THOUGHTBOMB', 'NEEDLEBLAST'
    ],
    'BALLMOVE': [
        'AURASPHERE', 'ELECTROBALL', 'ENERGYBALL', 'GYROBALL', 'ICEBALL', 'ROLLOUT',
        'MISTBALL', 'PYROBALL', 'SHADOWBALL', 'WEATHERBALL'
    ],
    'EXPLOSIVEMOVE': [
        'EXPLOSION', 'SELFDESTRUCT', 'MINDBLOWN', 'MISTYEXPLOSION'
    ],
    'AURAPULSEMOVE': [
        'AURASPHERE', 'DARKPULSE', 'DRAGONPULSE', 'TERRAINPULSE', 'WATERPULSE', 'ORIGINPULSE'
    ],
    'CANNONMOVE': [
        'ZAPCANNON', 'FLASHCANNON', 'HYDROCANNON', 'FLEURCANNON', 'DYNAMAXCANNON',
        'CORALBURST', 'SHELLSHOCK'
    ],
    'LIGHTMOVE': [
        'FLASH', 'FLASHCANNON', 'MIRRORSHOT', 'MOONBLAST', 'POWERGEM', 'SOLARBLADE',
        'SOLARBEAM', 'SWIFT', 'DAZZLINGGLEAM', 'FLASHFREEZE', 'LUSTERPURGE', 'SUNSTEELSTRIKE',
        'TECHNOBLAST', 'PRISMATICLASER', 'DOOMDESIRE', 'DIAMONDSTORM', 'PHOTONGEYSER',
        'LIGHTOFRUIN', 'SEARINGSUNRAZESMASH', 'LIGHTTHATBURNSTHESKY', 'TERABLAST', 'TERASTARSTORM'
    ],
    'BEAMMOVE': [
        'AURORABEAM', 'BUBBLEBEAM', 'CHARGEBEAM', 'ETERNABEAM', 'FICKLEBEAM', 'HYPERBEAM',
        'DYNAMAXCANNON', 'FLEURCANNON', 'ICEBEAM', 'LIGHTOFRUIN', 'MENACINGMOONRAZEMAELSTROM',
        'METEORBEAM', 'MOONGEISTBEAM', 'ORIGINPULSE', 'PSYBEAM', 'SIGNALBEAM', 'SOLARBEAM',
        'SIMPLEBEAM', 'STEELBEAM', 'TECHNOBLAST', 'TWINBEAM', 'TRIATTACK', 'TRINITYFORCE',
        'STARDESTROYER', 'SCRUTINIZE', 'REDSUNZENITH', 'SLOUGHRAY'
    ],
    'PINNINGMOVE': [
        'BODYSLAM', 'STOMP', 'DRAGONRUSH', 'STEAMROLLER', 'SUBMISSION', 'HEATCRASH',
        'HEAVYSLAM', 'FLYINGPRESS', 'ASTONISH', 'EXTRASENSORY', 'SHADOWFORCE', 'PHANTOMFORCE',
        'DOUBLEIRONBASH', 'SUPERCELLSLAM', 'GLACIALSLAM', 'MALICIOUSMOONSAULT', 'GRAVAPPLE'
    ],
    'WINDMOVE': [
        'AEROBLAST', 'AIRCUTTER', 'BLEAKWINDSTORM', 'BLIZZARD', 'FAIRYWIND', 'GUST',
        'HEATWAVE', 'HURRICANE', 'ICYWIND', 'OMINOUSWIND', 'PETALBLIZZARD', 'RAZORWIND',
        'SANDSEARSTORM', 'SANDSTORM', 'SILVERWIND', 'SPRINGTIDESTORM', 'TWISTER',
        'WILDBOLTSTORM', 'WINDVORTEX', 'STRATOSPHERE', 'JETSTREAM'
    ],
    'SOUNDMOVE': [
        'ALLURINGVOICE', 'BOOMBURST', 'BUGBUZZ', 'CHATTER', 'CLANGINGSCALES',
        'CLANGOROUSSOUL', 'CONFIDE', 'DISARMINGVOICE', 'ECHOEDVOICE', 'EERIESPELL',
        'GRASSWHISTLE', 'GROWL', 'HEALBELL', 'HOWL', 'HYPERVOICE', 'METALSOUND',
        'NOBLEROAR', 'OVERDRIVE', 'PARTINGSHOT', 'PERISHSONG', 'PSYCHICNOISE', 'RELICSONG',
        'ROAR', 'ROUND', 'SCREECH', 'SING', 'SNARL', 'SNORE', 'SPARKLINGARIA', 'SUPERSONIC',
        'TORCHSONG', 'UPROAR', 'BREAKDOWN', 'BOAST', 'SONICSCREAM', 'BATTLECRY', 'BELLOW',
        'NATURESCALL', 'CIRCADIANRHYTHM', 'FAERIEFIB', 'FRACTURE'
    ],
    'BITEMOVE': [
        'BITE', 'CRUNCH', 'FIREFANG', 'FISHIOUSREND', 'HYPERFANG', 'ICEFANG', 'JAWLOCK',
        'POISONFANG', 'PSYCHICFANGS', 'THUNDERFANG', 'SWEETTOOTH', 'PESTILENCE'
    ],
    'DANCEMOVE': [
        'AQUASTEP', 'CLANGOROUSSOUL', 'DRAGONDANCE', 'FEATHERDANCE', 'FIERYDANCE',
        'LUNARDANCE', 'PETALDANCE', 'QUIVERDANCE', 'REVELATIONDANCE', 'SWORDSDANCE',
        'TEETERDANCE', 'VICTORYDANCE', 'PYRETICRITUAL', 'SWANDIVE', 'RITEOFSPRING'
    ],
    'POWDERMOVE': [
        'COTTONSPORE', 'MAGICPOWDER', 'POISONPOWDER', 'POWDER', 'RAGEPOWDER',
        'SLEEPPOWDER', 'SPORE', 'STUNSPORE', 'SPRITZ'
    ],
    'WHIPMOVE': [
        'POWERWHIP', 'VINEWHIP', 'FIRELASH', 'SLOBBER'
    ],
    'CLAWMOVE': [
        'CRUSHCLAW', 'DIRECLAW', 'DRAGONCLAW', 'METALCLAW', 'SHADOWCLAW'
    ],
    'MOMENTUMMOVE': [
        'ICEBALL', 'ROLLOUT', 'LUNGE', 'STEAMROLLER', 'FEINT', 'DEFENSECURL',
        'FLAMEWHEEL', 'RAPIDSPIN', 'MORTALSPIN', 'BIDE'
    ],
    'SCENTMOVE': [
        'SWEETSCENT', 'AROMATHERAPY', 'SPRITZ'
    ],
    'SCALINGMOVE': [
        'BOUNCE', 'FLY', 'FLYINGPRESS', 'HIJUMPKICK', 'MAGNETRISE', 'SKYDROP',
        'SPLASH', 'ROCKCLIMB', 'WATERFALL'
    ],
    'DISPLACEMENTMOVE': [
        'PSYCHIC', 'STRENGTH', 'SKYDROP', 'BULLDOZE', 'STEAMROLLER', 'HEADBUTT',
        'ZENHEADBUTT', 'IRONHEAD', 'HEADSMASH', 'HEADCHARGE'
    ],
    'TRANSPORTMOVE': [
        'FLY', 'DIG', 'TELEPORT', 'PHANTOMFORCE', 'SHADOWFORCE'
    ]
}

# Print the categories in a format ready for PBStuff.rb
print("# Updated move categories")
print()
for cat_name in sorted(categories.keys()):
    moves = categories[cat_name]
    print(f"  {cat_name} = [")

    # Format with 4 moves per line for readability
    for i in range(0, len(moves), 4):
        chunk = moves[i:i+4]
        line_parts = [f"PBMoves::{move}" for move in chunk]
        line = "    " + ",".join(line_parts)
        if i + 4 < len(moves):
            line += ","
        print(line)

    print("  ]")

print()
print(f"# Total categories: {len(categories)}")
